<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Categorie extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Categorie_model');
 } 
 /*
* Listing of categorie
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['categorie'] = $this->Categorie_model->get_all_categorie();
      $data['_view'] = 'categorie/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Categorie Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new categorie
  */
 function add()
 {  
try{
      $params = array(
       'nom_categorie'=> $this->input->post('nom_categorie'),
       'description'=> $this->input->post('description'),
       'created_at'=> $this->input->post('created_at'),
       'updated_at'=> $this->input->post('updated_at'),
       'deleted_at'=> $this->input->post('deleted_at'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $id_categorie= $this->Categorie_model->add_categorie($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('categorie/index');
        }
        else
        { 
           $data['_view'] = 'categorie/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Categorie Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a categorie
 */
 public function edit($id_categorie)
 {   
  try{
   $data['categorie'] = $this->Categorie_model->get_categorie($id_categorie);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['categorie']['id_categorie']))
      {
        $params = array(
           'nom_categorie'=> $this->input->post('nom_categorie'),
           'description'=> $this->input->post('description'),
           'created_at'=> $this->input->post('created_at'),
           'updated_at'=> $this->input->post('updated_at'),
           'deleted_at'=> $this->input->post('deleted_at'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Categorie_model->update_categorie($id_categorie,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('categorie/index');
           }
           else
          {
              $data['_view'] = 'categorie/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The categorie you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Categorie Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting categorie
  */
  function remove($id_categorie)
   {
    try{
      $categorie = $this->Categorie_model->get_categorie($id_categorie);
  // check if the categorie exists before trying to delete it
       if(isset($categorie['id_categorie']))
       {
         $this->Categorie_model->delete_categorie($id_categorie);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('categorie/index');
       }
       else
       show_error('The categorie you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Categorie Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a categorie
 */
 public function view_more($id_categorie)
 {   
try{
   $data['categorie'] = $this->Categorie_model->get_categorie($id_categorie);
     if(isset($data['categorie']['id_categorie']))
      {
              $data['_view'] = 'categorie/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The categorie you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Categorie Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of categorie
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['categorie'] = $this->Categorie_model->get_all_categorie_by_cat($column_name,$value_id);
      $data['_view'] = 'categorie/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- categorie
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Categorie_model->update_categorie($id,$params);
   $data['noof_page'] = 0;
  $data['categorie'] = $this->Categorie_model->get_all_categorie();
  $this->load->view('categorie/index',$data);
}
 }
