<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Generatekey extends CI_Controller{
		function __construct()
		{
			parent::__construct();
			$this->load->model('Utilisateurs_model');
			$this->load->model('Posts_model');
			$this->load->model('Categorie_model');
			$this->load->helper('date');
		} 
		/*
		* Listing of utilisateurs
		*/
		public function index()
		{
			try
            {
				$data['utilisateurs'] = $this->Utilisateurs_model->getoken();
                // var_dump($data);exit;
                $data['_view'] = 'genkey';
                $this->load->view('layouts/main',$data);
			} 
            catch (Exception $ex) {
				throw new Exception('Utilisateurs Controller : Error in index function - ' . $ex);
			}  
		}
        public function generate(){
            $length = 10;
            $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
            $charactersLength = strlen($characters);
            $randomString = '';
            for ($i = 0; $i < $length; $i++) {
                $randomString .= $characters[rand(0, $charactersLength - 1)];
            }
            $params=array(
               'key'=> $randomString
            );
            $this->Utilisateurs_model->update_utilisateurs($_SESSION['id_utilisateur'],$params);
            redirect('genkey');
        }
		/*
		* Adding a new utilisateurs
		*/
 
}
