<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Profil extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Profil_model');
 } 
 /*
* Listing of profil
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['profil'] = $this->Profil_model->get_all_profil();
      $data['_view'] = 'profil/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Profil Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new profil
  */
 function add()
 {  
try{
      $params = array(
       'nom_profil'=> $this->input->post('nom_profil'),
       'created_at'=>'',
          'updated_at'=>DATE,
       'deleted_at'=>'',
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $id_profil= $this->Profil_model->add_profil($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('profil/index');
        }
        else
        { 
           $data['_view'] = 'profil/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Profil Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a profil
 */
 public function edit($id_profil)
 {   
  try{
   $data['profil'] = $this->Profil_model->get_profil($id_profil);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['profil']['id_profil']))
      {
        $params = array(
           'nom_profil'=> $this->input->post('nom_profil'),
            'created_at'=>'',
       'updated_at'=>DATE,
            'deleted_at'=>'',
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Profil_model->update_profil($id_profil,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('profil/index');
           }
           else
          {
              $data['_view'] = 'profil/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The profil you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Profil Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting profil
  */
  function remove($id_profil)
   {
    try{
      $profil = $this->Profil_model->get_profil($id_profil);
  // check if the profil exists before trying to delete it
       if(isset($profil['id_profil']))
       {
         $this->Profil_model->delete_profil($id_profil);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('profil/index');
       }
       else
       show_error('The profil you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Profil Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a profil
 */
 public function view_more($id_profil)
 {   
try{
   $data['profil'] = $this->Profil_model->get_profil($id_profil);
     if(isset($data['profil']['id_profil']))
      {
              $data['_view'] = 'profil/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The profil you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Profil Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of profil
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['profil'] = $this->Profil_model->get_all_profil_by_cat($column_name,$value_id);
      $data['_view'] = 'profil/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- profil
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Profil_model->update_profil($id,$params);
   $data['noof_page'] = 0;
  $data['profil'] = $this->Profil_model->get_all_profil();
  $this->load->view('profil/index',$data);
}
 }
