<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Welcome extends CI_Controller{
		function __construct()
		{
			parent::__construct();
			$this->load->model('Utilisateurs_model');
			$this->load->model('Posts_model');
			$this->load->model('Categorie_model');
			$this->load->helper('date');
		} 
		/*
		* Listing of utilisateurs
		*/
		public function index()
		{
			try{
				$data['noof_page'] = 0;
				$data['utilisateurs'] = $this->Utilisateurs_model->get_all_with_asso_utilisateurs();
				$data['categories'] = $this->Categorie_model->get_all_categorie();
				$data['posts'] = $this->Posts_model->get_all_with_asso_posts();
				$data['posts_10'] = $this->Posts_model->get_all_with_asso_posts_10();
				$data['posts_4'] = $this->Posts_model->get_all_with_asso_posts_4();
				// $data['posts'] = $this->Posts_model->get_all_with_asso_posts();
				// $date = new date_create();echo $date->format('d-m-Y');
				$data['today']=date("d.m.y");
				// var_dump($data['posts_10']);exit;
				$this->load->view('webpages/welcome',$data);
				} catch (Exception $ex) {
				throw new Exception('Utilisateurs Controller : Error in index function - ' . $ex);
			}  
		}
		/*
		* Adding a new utilisateurs
		*/
 
}
