
package memberwsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MemberWSDL", targetNamespace = "urn:MemberWSDL", wsdlLocation = "http://localhost/site_actualite/index.php/soap/nuSoapServer/getMembers?wsdl")
public class MemberWSDL
    extends Service
{

    private final static URL MEMBERWSDL_WSDL_LOCATION;
    private final static WebServiceException MEMBERWSDL_EXCEPTION;
    private final static QName MEMBERWSDL_QNAME = new QName("urn:MemberWSDL", "MemberWSDL");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/site_actualite/index.php/soap/nuSoapServer/getMembers?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEMBERWSDL_WSDL_LOCATION = url;
        MEMBERWSDL_EXCEPTION = e;
    }

    public MemberWSDL() {
        super(__getWsdlLocation(), MEMBERWSDL_QNAME);
    }

    public MemberWSDL(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEMBERWSDL_QNAME, features);
    }

    public MemberWSDL(URL wsdlLocation) {
        super(wsdlLocation, MEMBERWSDL_QNAME);
    }

    public MemberWSDL(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEMBERWSDL_QNAME, features);
    }

    public MemberWSDL(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MemberWSDL(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MemberWSDLPortType
     */
    @WebEndpoint(name = "MemberWSDLPort")
    public MemberWSDLPortType getMemberWSDLPort() {
        return super.getPort(new QName("urn:MemberWSDL", "MemberWSDLPort"), MemberWSDLPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberWSDLPortType
     */
    @WebEndpoint(name = "MemberWSDLPort")
    public MemberWSDLPortType getMemberWSDLPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:MemberWSDL", "MemberWSDLPort"), MemberWSDLPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEMBERWSDL_EXCEPTION!= null) {
            throw MEMBERWSDL_EXCEPTION;
        }
        return MEMBERWSDL_WSDL_LOCATION;
    }

}
