
package memberwsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MemberWSDLPortType", targetNamespace = "urn:MemberWSDL")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MemberWSDLPortType {


    /**
     * retourne les informations des utilisateurs
     * 
     * @param id
     * @return
     *     returns memberwsdl.Member
     */
    @WebMethod(action = "urn:MemberWSDL#getMember")
    @WebResult(partName = "return")
    public Member getMember(
        @WebParam(name = "id", partName = "id")
        int id);

    /**
     * Returns the information of a certain member
     * 
     * @param token
     * @return
     *     returns memberwsdl.Member
     */
    @WebMethod(action = "urn:MemberWSDL#getUsers")
    @WebResult(partName = "return")
    public Member getUsers(
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * Returns the information of a certain member
     * 
     * @param pass
     * @param user
     * @return
     *     returns memberwsdl.Member
     */
    @WebMethod(action = "urn:MemberWSDL#getUsers")
    @WebResult(partName = "return")
    public Member checkcredential(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "pass", partName = "pass")
        String pass);

    /**
     * Returns the information of a certain member
     * 
     * @param pass
     * @param user
     * @param prenom
     * @param nom
     * @param token
     * @return
     *     returns memberwsdl.Member
     */
    @WebMethod(action = "urn:MemberWSDL#getUsers")
    @WebResult(partName = "return")
    public Member ajouter(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "prenom", partName = "prenom")
        String prenom,
        @WebParam(name = "nom", partName = "nom")
        String nom,
        @WebParam(name = "pass", partName = "pass")
        String pass,
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * Returns the information of a certain member
     * 
     * @param id
     * @param token
     * @return
     *     returns memberwsdl.Member
     */
    @WebMethod(action = "urn:MemberWSDL#getUsers")
    @WebResult(partName = "return")
    public Member supprimer(
        @WebParam(name = "id", partName = "id")
        int id,
        @WebParam(name = "token", partName = "token")
        String token);

    /**
     * Returns the information of a certain member
     * 
     * @param pass
     * @param id
     * @param user
     * @param prenom
     * @param nom
     * @param token
     * @return
     *     returns memberwsdl.Member
     */
    @WebMethod(action = "urn:MemberWSDL#getUsers")
    @WebResult(partName = "return")
    public Member modifier(
        @WebParam(name = "id", partName = "id")
        int id,
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "prenom", partName = "prenom")
        String prenom,
        @WebParam(name = "nom", partName = "nom")
        String nom,
        @WebParam(name = "pass", partName = "pass")
        String pass,
        @WebParam(name = "token", partName = "token")
        String token);

}
