<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Profil extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Profil_model');
 } 
 /*
* Listing of profil
 */
public function get_all_post()
{
  try{
  $data['profil'] = $this->Profil_model->get_all_profil();
     if($data['profil'] && $data['profil']!=null){
       $profil_ar = array();
       foreach($data['profil'] as $p)
       {
       $p_ar = array();
       $p_ar['nom_profil'] = $p['nom_profil'];
       $profil_ar[] = $p_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $profil_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Profil controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new profil
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'nom_profil'=> $this->input->post('nom_profil'),
       'created_at'=>'',
       'updated_at'=>DATE,
       'deleted_at'=>'',
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $id_profil= $this->Profil_model->add_profil($params);
   $data['profil'] = $this->Profil_model->get_profil($id_profil);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Profil controller_name : Error in new profil function - ' . $ex);
       }  
 }  
  /*
  * Editing a profil
 */
  function edit_post($id_profil)
 {   
  try{
   $data['profil'] = $this->Profil_model->get_profil($id_profil);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['profil']['id_profil']))
      {
        $params = array(
           'nom_profil'=> $this->input->post('nom_profil'),
            'created_at'=>'',
            'updated_at'=>'',
            'deleted_at'=>'',
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Profil_model->update_profil($id_profil,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $id_profil
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $id_profil
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Profil controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting profil
  */
  function remove_post($id_profil)
   {
  try{
      $profil = $this->Profil_model->get_profil($id_profil);
  // check if the profil exists before trying to delete it
       if(isset($profil['id_profil']))
       {
         $this->Profil_model->delete_profil($id_profil);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $id_profil
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $id_profil
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Profil controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
