<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Categorie_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get categorie by id_categorie 
      */ 
      function get_categorie($id_categorie)
      {
        try{
           return $this->db->get_where('categorie',array('id_categorie'=>$id_categorie))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Categorie_model Model : Error in get_categorie function - ' . $ex);
           }  
      }
      /*
        * Get categorie by  column name
      */ 
      function get_categoriebyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('categorie',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Categorie_model Madel : Error in get_categoriebyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All categorie count 
      */ 
      function get_all_categorie_count()
      {
        try{
           $this->db->from('categorie');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Categorie_model model : Error in get_all_categorie_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join categoriecount 
      */ 
      function get_all_with_asso_categorie()
      {
        try{
          $query = $this->db->get('categorie'); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Categorie_model model : Error in get_all_with_asso_categorie function - ' . $ex);
           }  
      }
      /*
          * Get all categorie 
      */ 
      function get_all_categorie($params = array())
      {
        try{
              $this->db->order_by('id_categorie', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('categorie')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Categorie_model model : Error in get_all_categorie function - ' . $ex);
           }  
      } 
      /*
         * function to add new categorie 
      */
      function add_categorie($params)
      {
        try{
          $this->db->insert('categorie',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Categorie_model model : Error in add_categorie function - ' . $ex);
           }  
      }
      /* 
          * function to update categorie 
      */
      function update_categorie($id_categorie,$params)
      {
        try{
            $this->db->where('id_categorie',$id_categorie);
        return $this->db->update('categorie',$params);
           } catch (Exception $ex) {
             throw new Exception('Categorie_model model : Error in update_categorie function - ' . $ex);
           }  
       }
     /* 
          * function to delete categorie 
      */
       function delete_categorie($id_categorie)
       {
        try{
             return $this->db->delete('categorie',array('id_categorie'=>$id_categorie));
           } catch (Exception $ex) {
             throw new Exception('Categorie_model model : Error in delete_categorie function - ' . $ex);
           }  
       }
      /*
        * Get categorie by  column name where not in particular id
      */ 
      function get_categoriebyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('id_categorie!=', $where_cond);
           return $this->db->get_where('categorie',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Categorie_model model : Error in get_categoriebyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join categoriecount 
      */ 
      function get_all_with_asso_categorie_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Categorie_model model : Error in get_all_with_asso_categorie_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all categorie_by_cat 
      */ 
      function get_all_categorie_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('id_categorie', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('categorie')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Categorie_model model : Error in get_all_categorie_by_cat function - ' . $ex);
           }  
      } 
 }
