<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class User_info extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get utilisateurs by id_utilisateur 
      */ 
      function get_utilisateurs($id_utilisateur)
      {
        try{
           return $this->db->get_where('utilisateurs',array('id_utilisateur'=>$id_utilisateur))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Utilisateurs_model Model : Error in get_utilisateurs function - ' . $ex);
           }  
      }
      /*
        * Get utilisateurs by  column name
      */ 
      function get_utilisateursbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('utilisateurs',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Utilisateurs_model Madel : Error in get_utilisateursbyclm_name function - ' . $ex);
           }  
      }

      function getValidLogins(){
            try{
                return $this->db->query('SELECT nom_utilisateur as username, password FROM utilisateurs WHERE id_profil = 1')->row_array();
            } catch (Exception $ex) {
                throw new Exception('Utilisateurs_model Model : Error in get_utilisateurs function - ' . $ex);
            } 
      }
     /*
        * Get All utilisateurs count 
      */ 
      function get_all_utilisateurs_count()
      {
        try{
           $this->db->from('utilisateurs');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Utilisateurs_model model : Error in get_all_utilisateurs_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join utilisateurscount 
      */ 
      function get_all_with_asso_utilisateurs()
      {
        try{
           $this->db->select('*');
           $this->db->from('utilisateurs a  ' );
            $this->db->join('profil b', 'b.id_profil=a. id_profil','left');
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Utilisateurs_model model : Error in get_all_with_asso_utilisateurs function - ' . $ex);
           }  
      }
      /*
          * Get all utilisateurs 
      */ 
      function get_all_utilisateurs($params = array())
      {
        try{
              $this->db->order_by('id_utilisateur', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('utilisateurs')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Utilisateurs_model model : Error in get_all_utilisateurs function - ' . $ex);
           }  
      } 
      /*
         * function to add new utilisateurs 
      */
      function add_utilisateurs($params)
      {
        try{
          $this->db->insert('utilisateurs',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Utilisateurs_model model : Error in add_utilisateurs function - ' . $ex);
           }  
      }
      /* 
          * function to update utilisateurs 
      */
      function update_utilisateurs($id_utilisateur,$params)
      {
        try{
            $this->db->where('id_utilisateur',$id_utilisateur);
        return $this->db->update('utilisateurs',$params);
           } catch (Exception $ex) {
             throw new Exception('Utilisateurs_model model : Error in update_utilisateurs function - ' . $ex);
           }  
       }
     /* 
          * function to delete utilisateurs 
      */
       function delete_utilisateurs($id_utilisateur)
       {
        try{
             return $this->db->delete('utilisateurs',array('id_utilisateur'=>$id_utilisateur));
           } catch (Exception $ex) {
             throw new Exception('Utilisateurs_model model : Error in delete_utilisateurs function - ' . $ex);
           }  
       }
      /*
        * Get utilisateurs by  column name where not in particular id
      */ 
      function get_utilisateursbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('id_utilisateur!=', $where_cond);
           return $this->db->get_where('utilisateurs',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Utilisateurs_model model : Error in get_utilisateursbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join utilisateurscount 
      */ 
      function get_all_with_asso_utilisateurs_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
           $this->db->select('*');
           $this->db->from('utilisateurs a  ' );
              //$this->db->where($column_name, $value_id);
            $this->db->join('profil b', 'b.id_profil=a. id_profil','left');
              $this->db->where('a.'.$column_name, $value_id);
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Utilisateurs_model model : Error in get_all_with_asso_utilisateurs_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all utilisateurs_by_cat 
      */ 
      function get_all_utilisateurs_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('id_utilisateur', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('utilisateurs')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Utilisateurs_model model : Error in get_all_utilisateurs_by_cat function - ' . $ex);
           }  
      } 
 }
